### ISSUE TITLE
how to understand the following line of code?

### ISSUE THREAD

**Issue by gaopengcuhk** [lioutasb/TaLKConvolutions#3]
const scalar_t S_output = ((1.0 - alpha_right)*input[ind_floor_right][batchIdx][rIdx] + 
        	alpha_right*input[ind_ceil_right][batchIdx][rIdx]) - 
        	(alpha_left*((ind_floor_left-1 < 0)?static_cast<scalar_t>(0.0):input[ind_floor_left-1][batchIdx][rIdx]) + 
        	(1.0 - alpha_left)*((ind_ceil_left-1 < 0)?static_cast<scalar_t>(0.0):input[ind_ceil_left-1][batchIdx][rIdx]));

How to understand the following code?
((ind_floor_left-1 < 0)?static_cast<scalar_t>(0.0):input[ind_floor_left-1][batchIdx][rIdx]
(ind_ceil_left-1 < 0)?static_cast<scalar_t>(0.0):input[ind_ceil_left-1][batchIdx][rIdx])

**Comment by lioutasb** [comment]
The predicted absolute offset can be outside of the maximum length boundary to the left (negative index) because of minus one, thus we set "S_{alpha_L - 1}" from Equation 5 ([see the paper](https://arxiv.org/pdf/2002.03184.pdf)) to zero for these edge cases.
