### ISSUE TITLE
fp16 Training

### ISSUE THREAD

**Issue by RORO-ML** [lioutasb/TaLKConvolutions#4]
Hello,

thank you for this nice repo and paper.
Are you planning to add a full fp16 support for the talkconv_module scripts?

Regards :)

**Comment by lioutasb** [comment]
Hi @RORO-ML 

thanks a lot for your interest in our paper! The current implementation fully supports fp16. In fact, all the models trained for the experimental section of the paper used mixed-precision with Apex as implemented in the Fairseq framework.

Just as an example, you can see [here](https://github.com/lioutasb/TaLKConvolutions/blob/master/talkconv/talkconv_module/talk_convolution_cuda.cu#L152) (`AT_DISPATCH_FLOATING_TYPES_AND_HALF`) that the available CUDA kernels support all floating types including half-precision.

**Comment by RORO-ML** [comment]
Thank you, I was confused by the function annotations (`@amp.float_function`)
